import {ColorName, Settings} from './settings';
import {Shortcuts} from './shortcuts';
import {Environment} from '../../environment/environment';

export const DEFAULT_MAC_SHORTCUTS: Shortcuts = {
  aliases: [
    {
      command: 'cd ..',
      shortcut: 'Control+U'
    }
  ],
  showActions: 'Command+P',
  bringToFront: 'Command+F1',
  changeTab: 'Command+Tab',
  nextTab: 'Alt+Right',
  previousTab: 'Alt+Left',
  clearBuffer: 'Command+Alt+C',
  closeTab: 'Command+W',
  closeOtherTabs: 'Command+Shift+W',
  closeAllTabs: 'Control+Shift+Q',
  splitVertical: 'Command+Shift+<',
  splitAndMoveVertical: 'Command+<',
  splitHorizontal: 'Command+Shift+-',
  splitAndMoveHorizontal: 'Command+-',
  unsplit: 'Command+Shift+U',
  swapPanes: 'Command+Shift+P',
  abortTask: 'Control+C',
  abortAllTasks: 'Control+Shift+C',
  copy: 'Command+C',
  cut: 'Command+X',
  find: 'Command+F',
  clearLine: 'Control+Y',
  clearLineToEnd: 'Control+M',
  clearLineToStart: 'Control+N',
  deletePreviousWord: 'Control+,',
  deleteNextWord: 'Control+.',
  goToNextWord: 'Control+Right',
  goToPreviousWord: 'Control+Left',
  newTab: 'Command+T',
  duplicateTab: 'Command+Shift+D',
  paste: 'Command+V',
  showAutocompletion: 'Control+Space',
  showPasteHistory: 'Command+Shift+H',
  showKeytips: 'Control+K',
  showContextKeytips: 'Control+Shift+K',
  nextArgument: 'Control+Alt+Right',
  previousArgument: 'Control+Alt+Left',
  openSettings: 'Command+Shift+S',
  openShell1: 'Command+1',
  openShell2: 'Command+2',
  openShell3: 'Command+3',
  openShell4: 'Command+4',
  openShell5: 'Command+5',
  openShell6: 'Command+6',
  openShell7: 'Command+7',
  openShell8: 'Command+8',
  openShell9: 'Command+9',
  scrollToPreviousCommand: 'Control+Shift+Up',
  scrollToNextCommand: 'Control+Shift+Down',
  scrollToPreviousBookmark: 'Control+Alt+Up',
  scrollToNextBookmark: 'Control+Alt+Down',
  selectTextRight: 'Shift+Right',
  selectTextLeft: 'Shift+Left',
  selectWordRight: 'Control+Shift+Right',
  selectWordLeft: 'Control+Shift+Left',
  selectTextToEndOfLine: 'Shift+End',
  selectTextToStartOfLine: 'Shift+Home',
  openDevTools: 'Control+Shift+F12',
  injectPassword: 'Control+Shift+F'
}

export const DEFAULT_SHORTCUTS: Shortcuts = {
  aliases: [
    {
      command: 'cd ..',
      shortcut: 'Control+U'
    }
  ],
  showActions: 'Control+P',
  bringToFront: 'Control+F1',
  changeTab: 'Control+Tab',
  nextTab: 'Alt+Right',
  previousTab: 'Alt+Left',
  clearBuffer: 'Control+Alt+C',
  closeTab: 'Control+W',
  closeOtherTabs: 'Control+Shift+W',
  closeAllTabs: 'Control+Shift+Q',
  splitVertical: 'Control+Shift+<',
  splitAndMoveVertical: 'Control+<',
  splitHorizontal: 'Control+Shift+-',
  splitAndMoveHorizontal: 'Control+-',
  unsplit: 'Control+Shift+U',
  swapPanes: 'Control+Shift+P',
  abortTask: 'Control+C',
  abortAllTasks: 'Control+Shift+C',
  copy: 'Control+C',
  cut: 'Control+X',
  find: 'Control+F',
  clearLine: 'Control+Y',
  clearLineToEnd: 'Control+M',
  clearLineToStart: 'Control+N',
  deletePreviousWord: 'Control+,',
  deleteNextWord: 'Control+.',
  goToNextWord: 'Control+Right',
  goToPreviousWord: 'Control+Left',
  newTab: 'Control+T',
  duplicateTab: 'Control+Shift+D',
  paste: 'Control+V',
  showAutocompletion: 'Control+Space',
  showPasteHistory: 'Control+Shift+H',
  showKeytips: 'Control+K',
  showContextKeytips: 'Control+Shift+K',
  nextArgument: 'Control+Alt+Right',
  previousArgument: 'Control+Alt+Left',
  openSettings: 'Control+Shift+S',
  openShell1: 'Control+1',
  openShell2: 'Control+2',
  openShell3: 'Control+3',
  openShell4: 'Control+4',
  openShell5: 'Control+5',
  openShell6: 'Control+6',
  openShell7: 'Control+7',
  openShell8: 'Control+8',
  openShell9: 'Control+9',
  scrollToPreviousCommand: 'Control+Shift+Up',
  scrollToNextCommand: 'Control+Shift+Down',
  scrollToPreviousBookmark: 'Control+Alt+Up',
  scrollToNextBookmark: 'Control+Alt+Down',
  selectTextRight: 'Shift+Right',
  selectTextLeft: 'Shift+Left',
  selectWordRight: 'Control+Shift+Right',
  selectWordLeft: 'Control+Shift+Left',
  selectTextToEndOfLine: 'Shift+End',
  selectTextToStartOfLine: 'Shift+Home',
  openDevTools: 'Control+Shift+F12',
  injectPassword: 'Control+Shift+F'
}

export const DEFAULT_SETTINGS: Settings = {
  general: {
    enableTelemetry: true,
    enablePasteOnRightClick: false,
    enableCopyOnSelect: false,
    openTabInSameDirectory: true,
    scrollbackLines: 100000,
    editor: {
      useCustomEditor: false,
      editorCommand: '',
      editorArgs: [],
    }
  },
  autocomplete: {
    ignore: [
      'cd ..',
      'cd .',
      'cd ~',
      'cd /'
    ],
    position: 'cursor',
    mode: 'always'
  },
  shells: [],
  remoteShells: [],
  shortcuts: Environment.isMacOs() ? DEFAULT_MAC_SHORTCUTS : DEFAULT_SHORTCUTS,
  themes: [
   {
      fontsize: 14,
      appFontsize: 14,
      appFontFamily: 'Roboto',
      prompt: '$',
      cursorWidth: 4,
      fontFamily: 'monospace',
      image: '',
      name: 'freya',
      author: 'Lars Wolfram',
      padding: '1',
      paddingAsArray: [1, 1, 1, 1],
      removeFullScreenAppPadding: true,
      isDefault: true,
      colors: {
        foreground: '#ffffff',
        background: '#0e1925',
        highlight: '#32d8c1',
        black: '#0e1925',
        red: '#fd1155',
        green: '#11d894',
        yellow: '#fede55',
        blue: '#34bbfe',
        magenta: '#e465d9',
        cyan: '#32d8c1',
        white: '#eeeeee',
        brightBlack: '#0e1925',
        brightRed: '#fd1155',
        brightGreen: '#11d894',
        brightYellow: '#fede55',
        brightBlue: '#34bbfe',
        brightMagenta: '#e465d9',
        brightCyan: '#32d8c1',
        brightWhite: '#eeeeee',
        cursor: '#32d8c1',
        promptColors: [{foreground: 'cyan', background: 'black'}, {foreground:  'cyan', background: 'black'}]
      },
      imageOpacity: 80,
      cursorBlink: true,
      imageBlur: 0,
      enableLigatures: false,
      enableWebgl: false,
      fontWeight: 'normal',
      fontWeightBold: 'bold',
      promptVersion: 1,
      cursorStyle: 'bar'
    }, {
      fontsize: 14,
      appFontsize: 14,
      appFontFamily: 'Roboto',
      prompt: '$',
      cursorWidth: 4,
      fontFamily: 'monospace',
      image: '',
      name: 'freya light',
      author: 'Lars Wolfram',
      padding: '1',
      paddingAsArray: [1, 1, 1, 1],
      removeFullScreenAppPadding: true,
      isDefault: false,
      colors: {
        foreground: '#1c1d26',
        background: '#ffffff',
        highlight: '#00a49a',
        black: '#1c1d26',
        red: '#ff7500',
        green: '#549e1f',
        yellow: '#e7cc00',
        blue: '#1b35ff',
        magenta: '#e44c65',
        cyan: '#00a49a',
        white: '#1c1d26',
        brightBlack: '#0b0b0b',
        brightRed: '#fc3c26',
        brightGreen: '#1ccb2b',
        brightYellow: '#d5c129',
        brightBlue: '#568dff',
        brightMagenta: '#e6788a',
        brightCyan: '#00cfc3',
        brightWhite: '#0b0b0b',
        cursor: '#00a49a',
        promptColors: [{foreground: 'cyan', background: 'black'}, {foreground:  'cyan', background: 'black'}]
      },
      imageOpacity: 80,
      cursorBlink: true,
      imageBlur: 0,
      enableLigatures: false,
      enableWebgl: false,
      fontWeight: 'normal',
      fontWeightBold: 'bold',
      promptVersion: 1,
      cursorStyle: 'bar'
    },
    {
      fontsize: 14,
      appFontsize: 14,
      appFontFamily: 'Roboto',
      prompt: '$',
      cursorWidth: 2,
      fontFamily: 'monospace',
      image: '',
      name: 'cogno dark',
      author: 'Lars Wolfram',
      isDefault: false,
      padding: '1',
      paddingAsArray: [1, 1, 1, 1],
      removeFullScreenAppPadding: true,
      colors: {
        foreground: '#ebdbb2',
        background: '#282828',
        highlight: '#689d6a',
        black: '#3c3836',
        red: '#cc241d',
        green: '#98971a',
        yellow: '#d79921',
        blue: '#458588',
        magenta: '#b16286',
        cyan: '#689d6a',
        white: '#ebdbb2',
        brightBlack: '#504945',
        brightRed: '#fb4934',
        brightGreen: '#b8bb26',
        brightYellow: '#fabd2f',
        brightBlue: '#83a598',
        brightMagenta: '#d3869b',
        brightCyan: '#8ec07c',
        brightWhite: '#fbf1c7',
        cursor: '#d79921',
        promptColors: [{foreground: 'cyan', background: 'black'}, {foreground:  'cyan', background: 'black'}]
      },
      imageOpacity: 80,
      cursorBlink: true,
      imageBlur: 0,
      enableLigatures: false,
      enableWebgl: false,
      fontWeight: 'normal',
      fontWeightBold: 'bold',
      promptVersion: 1,
      cursorStyle: 'bar'
    },
    {
      fontsize: 14,
      appFontsize: 14,
      appFontFamily: 'Roboto',
      prompt: '$',
      cursorWidth: 2,
      fontFamily: 'monospace',
      image: '',
      name: 'cogno light',
      author: 'Lars Wolfram',
      isDefault: false,
      padding: '1',
      paddingAsArray: [1, 1, 1, 1],
      removeFullScreenAppPadding: true,
      colors: {
        foreground: '#3c3836',
        background: '#fffbec',
        highlight: '#427b58',
        black: '#3c3836',
        red: '#9d0006',
        green: '#79740e',
        yellow: '#b57614',
        blue: '#076678',
        magenta: '#8f3f71',
        cyan: '#427b58',
        white: '#3c3836',
        brightBlack: '#7c6f64',
        brightRed: '#cc241d',
        brightGreen: '#98971a',
        brightYellow: '#d79921',
        brightBlue: '#458588',
        brightMagenta: '#b16286',
        brightCyan: '#689d6a',
        brightWhite: '#7c6f64',
        cursor: '#b57614',
        promptColors: [{foreground: 'cyan', background: 'black'}, {foreground:  'cyan', background: 'black'}]
      },
      imageOpacity: 80,
      cursorBlink: true,
      imageBlur: 0,
      enableLigatures: false,
      enableWebgl: false,
      fontWeight: 'normal',
      fontWeightBold: 'bold',
      promptVersion: 1,
      cursorStyle: 'bar'
    }
  ]
};
