"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ColorName = void 0;
var ColorName;
(function (ColorName) {
    ColorName["foreground"] = "foreground";
    ColorName["background"] = "background";
    ColorName["highlight"] = "highlight";
    ColorName["cursor"] = "cursor";
    ColorName["black"] = "black";
    ColorName["red"] = "red";
    ColorName["green"] = "green";
    ColorName["yellow"] = "yellow";
    ColorName["blue"] = "blue";
    ColorName["magenta"] = "magenta";
    ColorName["cyan"] = "cyan";
    ColorName["white"] = "white";
    ColorName["brightBlack"] = "brightBlack";
    ColorName["brightRed"] = "brightRed";
    ColorName["brightGreen"] = "brightGreen";
    ColorName["brightYellow"] = "brightYellow";
    ColorName["brightBlue"] = "brightBlue";
    ColorName["brightMagenta"] = "brightMagenta";
    ColorName["brightCyan"] = "brightCyan";
    ColorName["brightWhite"] = "brightWhite";
    ColorName["commandRunning"] = "commandRunning";
    ColorName["commandSuccess"] = "commandSuccess";
    ColorName["commandError"] = "commandError";
})(ColorName || (exports.ColorName = ColorName = {}));
