import type { CommandSpec, Generator, OptionSpec, SubcommandSpec, Suggestion } from "../spec.types";
const composerIcon = "https://getcomposer.org/img/logo-composer-transparent5.png";
interface ComposerArgument {
    name: string;
    is_required: boolean;
    is_array: boolean;
    description: string;
    default: null | string | Array<string>;
}
interface ComposerOption {
    name: string;
    shortcut: string;
    accept_value: boolean;
    is_value_required: boolean;
    is_multiple: boolean; // not supported by fig
    description: string;
    default: null | boolean; // not supported by fig
}
interface ComposerCommandDefinition {
    arguments: Record<string, ComposerArgument>;
    options: Record<string, ComposerOption>;
}
interface ComposerCommand {
    name: string;
    usage: string[]; // this is actually generated by fig
    description: string;
    help: string;
    definition: ComposerCommandDefinition;
}
interface ComposerListOutput {
    commands: ComposerCommand[];
}
const PACKAGE_REGEXP = new RegExp("^.*/.*$");
const searchGenerator: Generator = {
    script: function (context) {
        if (context[context.length - 1] === "")
            return undefined;
        const searchTerm = context[context.length - 1];
        return [
            "curl",
            "-s",
            "-H",
            "Accept: application/json",
            `https://packagist.org/search.json?q=${searchTerm}&per_page=20`
        ];
    },
    postProcess: function (out) {
        try {
            return JSON.parse(out).results.map((item) => ({
                name: item.name,
                description: item.description,
                icon: "📦",
            }) as Suggestion) as Suggestion[];
        }
        catch (e) {
            return [];
        }
    },
};
// generate package list from composer.json file
const packagesGenerator: Generator = {
    script: ["cat", "composer.json"],
    postProcess: function (out) {
        if (out.trim() == "") {
            return [];
        }
        try {
            const packageContent = JSON.parse(out);
            const dependencies = packageContent["require"] || {};
            const devDependencies = packageContent["require-dev"] || {};
            return filterRealDependencies(Object.assign(dependencies, devDependencies)).map((dependencyName) => ({
                name: dependencyName,
                icon: "📦",
            }));
        }
        catch (e) {
            console.log(e);
        }
        return [];
    },
};
function filterRealDependencies(dependencies) {
    return Object.keys(dependencies).filter((dependency) => dependency.match(PACKAGE_REGEXP));
}
const completionSpec: CommandSpec = {
    name: "composer",
    description: "Composer Command"
};
export default completionSpec;
