// Autogenerated by @fig/complete-commander
import type { CommandSpec } from "../spec.types";
const completionSpec: CommandSpec = {
    name: "create-completion-spec",
    description: "Setup fig folder and create spec with the given name",
    subcommands: [
        {
            name: "help",
            description: "Display help for command",
            args: { name: "command" }
        }
    ],
    options: [
        {
            name: "--here",
            description: "Set if the spec should be created in the current folder"
        },
        {
            name: ["-h", "--help"],
            description: "Display help for command"
        }
    ]
};
export default completionSpec;
