// Copyright (c) 2021-present 650 Industries, Inc. (aka Expo)
// Generated by running `yarn introspect fig` in expo-cli/packages/expo-cli
// expo-cli@4.13.0
import type { CommandSpec, Generator, Suggestion } from "../spec.types";
const _gen: Record<string, Generator> = {
    npm: {
        script(context) {
            if (context[context.length - 1] === "")
                return undefined;
            const searchTerm = context[context.length - 1];
            return [
                "curl",
                "-s",
                "-H",
                "Accept: application/json",
                `https://api.npms.io/v2/search?q=${searchTerm}&size=20`
            ];
        },
        postProcess(script: string) {
            try {
                const results: {
                    package: {
                        name: string;
                        description: string;
                    };
                    searchScore: number;
                }[] = JSON.parse(script).results;
                return results.map((item) => ({
                    name: item.package.name,
                    description: item.package.description,
                })) as Suggestion[];
            }
            catch (e) {
                return [];
            }
        },
    },
    "xcode-configuration": {
        script: ["bash", "-c", "xcodebuild -project ios/*.xcodeproj -list -json"],
        postProcess: (script: string) => JSON.parse(script).project.configurations.map((name) => ({ name })),
    },
    "xcode-scheme": {
        script: ["bash", "-c", "xcodebuild -project ios/*.xcodeproj -list -json"],
        postProcess: (script: string) => JSON.parse(script).project.schemes.map((name) => ({ name })),
    },
    "xcode-devices": {
        script: ["xcrun", "xctrace", "list", "devices"],
        postProcess: (script: string) => script
            .split("\n")
            .filter((item) => !item.match(/^=/))
            .filter(Boolean)
            .map((item) => item.split(/(.*?) (\(([0-9.]+)\) )?\(([0-9A-F-]+)\)/i))
            // filter catalyst
            .filter((item: string[] | null) => !!item?.[3])
            .map(([, name, , osVersion, udid]) => ({
            displayName: `${name.trim()} (${osVersion})`,
            name: udid,
        })),
    },
    "max-workers": {
        script: ["sysctl", "-n", "hw.ncpu"],
        postProcess: (script: string) => {
            const count = Number(script);
            return Array.from({ length: count }, (_, i) => {
                const v = count - i;
                return {
                    priority: v,
                    name: String(v),
                };
            });
        },
    },
};
const completionSpec: CommandSpec = {
    name: "expo-cli",
    description: "Tools for creating, running, and deploying Universal Expo and React Native apps",
    options: [
        {
            name: ["-h", "--help"],
            description: "Output usage information"
        },
        {
            name: ["-V", "--version"],
            description: "Output the version number"
        }
    ],
    subcommands: [
        {
            name: ["login", "signin"],
            description: "Login to an Expo account",
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-u", "--username"],
                    description: "Username",
                    args: {
                        name: "string"
                    }
                },
                {
                    name: ["-p", "--password"],
                    description: "Password",
                    args: {
                        name: "string"
                    }
                },
                {
                    name: "--otp",
                    description: "One-time password from your 2FA device",
                    args: {
                        name: "string"
                    }
                }
            ]
        },
        {
            name: "logout",
            description: "Logout of an Expo account",
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                }
            ]
        },
        {
            name: "register",
            description: "Sign up for a new Expo account",
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                }
            ]
        },
        {
            name: ["whoami", "w"],
            description: "Return the currently authenticated account",
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                }
            ]
        },
        {
            name: ["build:ios", "bi"],
            description: "Build and sign a standalone IPA for the Apple App Store",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-c", "--clear-credentials"],
                    description: "Clear all credentials stored on Expo servers",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--clear-dist-cert",
                    description: "Remove Distribution Certificate stored on Expo servers",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--clear-push-key",
                    description: "Remove Push Notifications Key stored on Expo servers",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--clear-push-cert",
                    description: "Remove Push Notifications Certificate stored on Expo servers. Use of Push Notifications Certificates is deprecated",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--clear-provisioning-profile",
                    description: "Remove Provisioning Profile stored on Expo servers",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-r", "--revoke-credentials"],
                    description: "Revoke credentials on developer.apple.com, select appropriate using --clear-* options",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--apple-id",
                    description: "Apple ID username (please also set the Apple ID password as EXPO_APPLE_PASSWORD environment variable)",
                    args: {
                        name: "login"
                    }
                },
                {
                    name: ["-t", "--type"],
                    description: "Type of build: [archive|simulator]",
                    args: {
                        name: "archive|simulator"
                    }
                },
                {
                    name: "--release-channel",
                    description: "Pull from specified release channel",
                    args: {
                        name: "name"
                    }
                },
                {
                    name: "--no-publish",
                    description: "Disable automatic publishing before building",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--no-wait",
                    description: "Exit immediately after scheduling build",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--team-id",
                    description: "Apple Team ID",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--dist-p12-path",
                    description: "Path to your Distribution Certificate P12 (set password as EXPO_IOS_DIST_P12_PASSWORD environment variable)",
                    args: {
                        name: "path"
                    }
                },
                {
                    name: "--push-id",
                    description: "Push Key ID (ex: 123AB4C56D)",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--push-p8-path",
                    description: "Path to your Push Key .p8 file",
                    args: {
                        name: "path"
                    }
                },
                {
                    name: "--provisioning-profile-path",
                    description: "Path to your Provisioning Profile",
                    args: {
                        name: "path"
                    }
                },
                {
                    name: "--public-url",
                    description: "The URL of an externally hosted manifest (for self-hosted apps)",
                    args: {
                        name: "url"
                    }
                },
                {
                    name: "--skip-credentials-check",
                    description: "Skip checking credentials",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--skip-workflow-check",
                    description: "Skip warning about build service bare workflow limitations",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: ["build:android", "ba"],
            description: "Build and sign a standalone APK or App Bundle for the Google Play Store",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-c", "--clear-credentials"],
                    description: "Clear stored credentials",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--release-channel",
                    description: "Pull from specified release channel",
                    args: {
                        name: "name"
                    }
                },
                {
                    name: "--no-publish",
                    description: "Disable automatic publishing before building",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--no-wait",
                    description: "Exit immediately after triggering build",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--keystore-path",
                    description: "Path to your Keystore: *.jks",
                    args: {
                        name: "path"
                    }
                },
                {
                    name: "--keystore-alias",
                    description: "Keystore Alias",
                    args: {
                        name: "alias"
                    }
                },
                {
                    name: "--generate-keystore",
                    description: "[deprecated] Generate Keystore if one does not exist",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--public-url",
                    description: "The URL of an externally hosted manifest (for self-hosted apps)",
                    args: {
                        name: "url"
                    }
                },
                {
                    name: "--skip-workflow-check",
                    description: "Skip warning about build service bare workflow limitations",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-t", "--type"],
                    description: "Type of build: [app-bundle|apk]",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "build:web",
            description: "Build the web app for production",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-c", "--clear"],
                    description: "Clear all cached build files and assets",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--no-pwa",
                    description: "Prevent webpack from generating the manifest.json and injecting meta into the index.html head",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-d", "--dev"],
                    description: "Turns dev flag on before bundling",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: ["build:status", "bs"],
            description: "Get the status of the latest build for the project",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--public-url",
                    description: "The URL of an externally hosted manifest (for self-hosted apps)",
                    args: {
                        name: "url"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "client:ios",
            description: "Deprecated in favor of Expo Dev Clients",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--apple-id",
                    description: "Apple ID username (please also set the Apple ID password as EXPO_APPLE_PASSWORD environment variable)",
                    args: {
                        name: "login"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "client:install:ios",
            description: "Install Expo Go for iOS on the simulator",
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--latest",
                    description: "Install the latest version of Expo Go, ignoring the current project version",
                    args: {
                        name: "boolean"
                    }
                }
            ]
        },
        {
            name: "client:install:android",
            description: "Install Expo Go for Android on a connected device or emulator",
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-d", "--device"],
                    description: "Device name to install the client on",
                    args: {
                        name: "device"
                    }
                },
                {
                    name: "--latest",
                    description: "Install the latest version of Expo Go, ignore the current project version",
                    args: {
                        name: "boolean"
                    }
                }
            ]
        },
        {
            name: "credentials:manager",
            description: "Manage your credentials",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-p", "--platform"],
                    description: "Platform: [android|ios]",
                    args: {
                        name: "platform"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "customize:web",
            description: "Eject the default web files for customization",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-f", "--force"],
                    description: "Allows replacing existing files",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--offline",
                    description: "Allows this command to run while offline",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "eject",
            description: "Create native iOS and Android project files. Learn more: https://docs.expo.dev/workflow/customizing/",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--no-install",
                    description: "Skip installing npm packages and CocoaPods",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--npm",
                    description: "Use npm to install dependencies. (default when Yarn is not installed)",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-p", "--platform"],
                    description: "Platforms to sync: ios, android, all. Default: all",
                    args: {
                        name: "platform"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "prebuild",
            description: "Create native iOS and Android project files before building natively. Learn more: https://docs.expo.dev/workflow/customizing/",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--no-install",
                    description: "Skip installing npm packages and CocoaPods",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--clean",
                    description: "Delete the native folders and regenerate them before applying changes",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--npm",
                    description: "Use npm to install dependencies. (default when Yarn is not installed)",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--template",
                    description: "Project template to clone from. File path pointing to a local tar file or a github repo",
                    args: {
                        name: "template"
                    }
                },
                {
                    name: ["-p", "--platform"],
                    description: "Platforms to sync: ios, android, all. Default: all",
                    args: {
                        name: "platform"
                    }
                },
                {
                    name: "--skip-dependency-update",
                    description: "Preserves versions of listed packages in package.json (comma separated list)",
                    args: {
                        name: "dependencies"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "bundle-assets",
            description: "Bundle assets for a detached app. This command should be executed from xcode or gradle",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--dest",
                    description: "Destination directory for assets",
                    args: {
                        name: "dest"
                    }
                },
                {
                    name: "--platform",
                    description: "Detached project platform",
                    args: {
                        name: "platform"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "prepare-detached-build",
            description: "Prepare a detached project for building",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--platform",
                    description: "Detached project platform",
                    args: {
                        name: "platform"
                    }
                },
                {
                    name: "--skipXcodeConfig",
                    description: "[iOS only] if true, do not configure Xcode project",
                    args: {
                        name: "bool"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "export",
            description: "Export the static files of the app for hosting it on a web server",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--platform",
                    description: "Platforms: android, ios, all",
                    args: {
                        name: "platform"
                    }
                },
                {
                    name: ["-p", "--public-url"],
                    description: "The public url that will host the static files (required)",
                    args: {
                        name: "url"
                    }
                },
                {
                    name: ["-c", "--clear"],
                    description: "Clear the Metro bundler cache",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--output-dir",
                    description: "The directory to export the static files to",
                    args: {
                        name: "dir"
                    }
                },
                {
                    name: ["-a", "--asset-url"],
                    description: "The absolute or relative url that will host the asset files",
                    args: {
                        name: "url"
                    }
                },
                {
                    name: ["-d", "--dump-assetmap"],
                    description: "Dump the asset map for further processing",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--dev",
                    description: "Configure static files for developing locally using a non-https server",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-s", "--dump-sourcemap"],
                    description: "Dump the source map for debugging the JS bundle",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-q", "--quiet"],
                    description: "Suppress verbose output",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-t", "--target"],
                    description: "Target environment for which this export is intended",
                    args: {
                        name: "managed|bare"
                    }
                },
                {
                    name: "--merge-src-dir",
                    description: "A repeatable source dir to merge in",
                    args: {
                        name: "dir"
                    }
                },
                {
                    name: "--merge-src-url",
                    description: "A repeatable source tar.gz file URL to merge in",
                    args: {
                        name: "url"
                    }
                },
                {
                    name: "--max-workers",
                    description: "Maximum number of tasks to allow Metro to spawn",
                    args: {
                        name: "Number of workers"
                    }
                },
                {
                    name: "--experimental-bundle",
                    description: "Export bundles for use with EAS updates",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "fetch:ios:certs",
            description: "Download the project's iOS standalone app signing credentials",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "fetch:android:keystore",
            description: "Download the project's Android keystore",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "fetch:android:hashes",
            description: "Compute and log the project's Android key hashes",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "fetch:android:upload-cert",
            description: "Download the project's Android keystore",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "config",
            description: "Show the project config",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-t", "--type"],
                    description: "Type of config to show",
                    args: {
                        name: "public|prebuild|introspect"
                    }
                },
                {
                    name: "--full",
                    description: "Include all project config data",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "diagnostics",
            description: "Log environment info to the console",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "doctor",
            description: "Diagnose issues with the project",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: ["upgrade", "update"],
            description: "Upgrade the project packages and config for the given SDK version",
            args: {
                name: "sdk-version"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--npm",
                    description: "Use npm to install dependencies. (default when package-lock.json exists)",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--yarn",
                    description: "Use Yarn to install dependencies. (default when yarn.lock exists)",
                    args: {
                        name: "boolean"
                    }
                }
            ]
        },
        {
            name: ["init", "i"],
            description: "Create a new Expo project",
            args: {
                name: "name"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-t", "--template"],
                    description: 'Specify which template to use. Valid options are "blank", "tabs", "bare-minimum" or a package on npm (e.g. "expo-template-bare-minimum") that includes an Expo project template',
                    args: {
                        name: "name"
                    }
                },
                {
                    name: "--npm",
                    description: "Use npm to install dependencies. (default when Yarn is not installed)",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--yarn",
                    description: "Use Yarn to install dependencies. (default when Yarn is installed)",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--no-install",
                    description: "Skip installing npm packages or CocoaPods",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--name",
                    description: "The name of your app visible on the home screen",
                    args: {
                        name: "name"
                    }
                },
                {
                    name: "--yes",
                    description: 'Use default options. Same as "expo init . --template blank',
                    args: {
                        name: "boolean"
                    }
                }
            ]
        },
        {
            name: ["install", "add"],
            description: "Install a module or other package to a project",
            args: {
                name: "packages"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--npm",
                    description: "Use npm to install dependencies. (default when package-lock.json exists)",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--yarn",
                    description: "Use Yarn to install dependencies. (default when yarn.lock exists)",
                    args: {
                        name: "boolean"
                    }
                }
            ]
        },
        {
            name: ["publish", "p"],
            description: "Deploy a project to Expo hosting",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-q", "--quiet"],
                    description: "Suppress verbose output from the Metro bundler",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-s", "--send-to"],
                    description: "A phone number or email address to send a link to",
                    args: {
                        name: "dest"
                    }
                },
                {
                    name: ["-c", "--clear"],
                    description: "Clear the Metro bundler cache",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-t", "--target"],
                    description: "Target environment for which this publish is intended. Options are `managed` or `bare`",
                    args: {
                        name: "managed|bare"
                    }
                },
                {
                    name: "--max-workers",
                    description: "Maximum number of tasks to allow Metro to spawn",
                    args: {
                        name: "Number of workers"
                    }
                },
                {
                    name: "--release-channel",
                    description: "The release channel to publish to. Default is 'default'",
                    args: {
                        name: "name"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: ["publish:set", "ps"],
            description: "Specify the channel to serve a published release",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-c", "--release-channel"],
                    description: "The channel to set the published release. (Required)",
                    args: {
                        name: "name"
                    }
                },
                {
                    name: ["-p", "--publish-id"],
                    description: "The id of the published release to serve from the channel. (Required)",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: ["publish:rollback", "pr"],
            description: "Undo an update to a channel",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--channel-id",
                    description: "This flag is deprecated",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-c", "--release-channel"],
                    description: "The channel to rollback from. (Required)",
                    args: {
                        name: "name"
                    }
                },
                {
                    name: ["-s", "--sdk-version"],
                    description: "The sdk version to rollback. (Required)",
                    args: {
                        name: "version"
                    }
                },
                {
                    name: ["-p", "--platform"],
                    description: "The platform to rollback",
                    args: {
                        name: "platform"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: ["publish:history", "ph"],
            description: "Log the project's releases",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-c", "--release-channel"],
                    description: "Filter by release channel. If this flag is not included, the most recent publications will be shown",
                    args: {
                        name: "name"
                    }
                },
                {
                    name: "--count",
                    description: "Number of logs to view, maximum 100, default 5",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-p", "--platform"],
                    description: "Filter by platform, android or ios. Defaults to both platforms",
                    args: {
                        name: "platform"
                    }
                },
                {
                    name: ["-s", "--sdk-version"],
                    description: "Filter by SDK version e.g. 35.0.0",
                    args: {
                        name: "version"
                    }
                },
                {
                    name: ["-r", "--raw"],
                    description: "Produce some raw output",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: ["publish:details", "pd"],
            description: "Log details of a published release",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--publish-id",
                    description: "Publication id. (Required)",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-r", "--raw"],
                    description: "Produce some raw output",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "push:android:upload",
            description: "Upload an FCM key for Android push notifications",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--api-key",
                    description: "Server API key for FCM",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "push:android:show",
            description: "Log the value currently in use for FCM notifications for this project",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "push:android:clear",
            description: "Delete a previously uploaded FCM credential",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "run:android",
            description: "Run the Android app binary locally",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--no-bundler",
                    description: "Skip starting the Metro bundler",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-d", "--device"],
                    description: "Device name to build the app on",
                    args: {
                        name: "device"
                    }
                },
                {
                    name: ["-p", "--port"],
                    description: "Port to start the Metro bundler on. Default: 8081",
                    args: {
                        name: "port"
                    }
                },
                {
                    name: "--variant",
                    description: "(Android) build variant",
                    args: {
                        name: "name"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "run:ios",
            description: "Run the iOS app binary locally",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--no-build-cache",
                    description: "Clear the native derived data before building",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--no-install",
                    description: "Skip installing dependencies",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--no-bundler",
                    description: "Skip starting the Metro bundler",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-d", "--device"],
                    description: "Device name or UDID to build the app on",
                    args: {
                        name: "device"
                    }
                },
                {
                    name: ["-p", "--port"],
                    description: "Port to start the Metro bundler on. Default: 8081",
                    args: {
                        name: "port"
                    }
                },
                {
                    name: "--scheme",
                    description: "Scheme to build",
                    args: {
                        name: "scheme"
                    }
                },
                {
                    name: "--configuration",
                    description: "Xcode configuration to use. Debug or Release. Default: Debug",
                    args: {
                        name: "configuration"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "send",
            description: "Share the project's URL to an email address",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-s", "--send-to"],
                    description: "Email address to send the URL to",
                    args: {
                        name: "dest"
                    }
                },
                {
                    name: "--dev-client",
                    description: "Experimental: Starts the bundler for use with the expo-development-client",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--scheme",
                    description: "Custom URI protocol to use with a development build",
                    args: {
                        name: "scheme"
                    }
                },
                {
                    name: ["-a", "--android"],
                    description: "Opens your app in Expo Go on a connected Android device",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-i", "--ios"],
                    description: "Opens your app in Expo Go in a currently running iOS simulator on your computer",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-w", "--web"],
                    description: "Opens your app in a web browser",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-m", "--host"],
                    description: 'Lan (default), tunnel, localhost. Type of host to use. "tunnel" allows you to view your link on other networks',
                    args: {
                        name: "mode"
                    }
                },
                {
                    name: "--tunnel",
                    description: "Same as --host tunnel",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--lan",
                    description: "Same as --host lan",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--localhost",
                    description: "Same as --host localhost",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: ["start", "r"],
            description: "Start a local dev server for the app",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: ["-s", "--send-to"],
                    description: "An email address to send a link to",
                    args: {
                        name: "dest"
                    }
                },
                {
                    name: ["-c", "--clear"],
                    description: "Clear the Metro bundler cache",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--max-workers",
                    description: "Maximum number of tasks to allow Metro to spawn",
                    args: {
                        name: "Number of workers"
                    }
                },
                {
                    name: "--dev",
                    description: "Turn development mode on",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--no-dev",
                    description: "Turn development mode off",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--minify",
                    description: "Minify code",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--no-minify",
                    description: "Do not minify code",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--https",
                    description: "To start webpack with https protocol",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--force-manifest-type",
                    description: "Override auto detection of manifest type",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-p", "--port"],
                    description: "Port to start the native Metro bundler on (does not apply to web or tunnel). Default: 19000",
                    args: {
                        name: "port"
                    }
                },
                {
                    name: "--no-https",
                    description: "To start webpack with http protocol",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--dev-client",
                    description: "Experimental: Starts the bundler for use with the expo-development-client"
                },
                {
                    name: "--scheme",
                    description: "Custom URI protocol to use with a development build",
                    args: {
                        name: "scheme"
                    }
                },
                {
                    name: ["-a", "--android"],
                    description: "Opens your app in Expo Go on a connected Android device",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-i", "--ios"],
                    description: "Opens your app in Expo Go in a currently running iOS simulator on your computer",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-w", "--web"],
                    description: "Opens your app in a web browser",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-m", "--host"],
                    description: 'Lan (default), tunnel, localhost. Type of host to use. "tunnel" allows you to view your link on other networks',
                    args: {
                        name: "mode"
                    }
                },
                {
                    name: "--tunnel",
                    description: "Same as --host tunnel",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--lan",
                    description: "Same as --host lan",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--localhost",
                    description: "Same as --host localhost",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--offline",
                    description: "Allows this command to run while offline",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: ["start:web", "web"],
            description: "Start a Webpack dev server for the web app",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--dev",
                    description: "Turn development mode on",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--no-dev",
                    description: "Turn development mode off",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--minify",
                    description: "Minify code",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--no-minify",
                    description: "Do not minify code",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--https",
                    description: "To start webpack with https protocol",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--no-https",
                    description: "To start webpack with http protocol",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--force-manifest-type",
                    description: "Override auto detection of manifest type",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-p", "--port"],
                    description: "Port to start the Webpack bundler on. Default: 19006",
                    args: {
                        name: "port"
                    }
                },
                {
                    name: ["-s", "--send-to"],
                    description: "An email address to send a link to",
                    args: {
                        name: "dest"
                    }
                },
                {
                    name: "--dev-client",
                    description: "Experimental: Starts the bundler for use with the expo-development-client",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--scheme",
                    description: "Custom URI protocol to use with a development build",
                    args: {
                        name: "scheme"
                    }
                },
                {
                    name: ["-a", "--android"],
                    description: "Opens your app in Expo Go on a connected Android device",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-i", "--ios"],
                    description: "Opens your app in Expo Go in a currently running iOS simulator on your computer",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-w", "--web"],
                    description: "Opens your app in a web browser",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-m", "--host"],
                    description: 'Lan (default), tunnel, localhost. Type of host to use. "tunnel" allows you to view your link on other networks',
                    args: {
                        name: "mode"
                    }
                },
                {
                    name: "--tunnel",
                    description: "Same as --host tunnel",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--lan",
                    description: "Same as --host lan",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--localhost",
                    description: "Same as --host localhost",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--offline",
                    description: "Allows this command to run while offline",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: ["upload:android", "ua"],
            description: "Moved to eas submit in eas-cli",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--verbose",
                    description: "Migrate to eas submit --verbose",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--latest",
                    description: "Migrate to eas submit --latest",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--id",
                    description: "Migrate to eas submit --id <id>",
                    args: {
                        name: "id"
                    }
                },
                {
                    name: "--path",
                    description: "Migrate to eas submit --path <path>",
                    args: {
                        name: "path"
                    }
                },
                {
                    name: "--url",
                    description: "Migrate to eas submit --url <url>",
                    args: {
                        name: "url"
                    }
                },
                {
                    name: "--android-package",
                    description: "Migrate to eas submit (android-package is auto inferred)",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--type",
                    description: "Migrate to eas submit (type is auto inferred)",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--key",
                    description: "Migrate to eas.json's serviceAccountKeyPath property",
                    args: {
                        name: "key"
                    }
                },
                {
                    name: "--track",
                    description: "Migrate to eas.json's track property",
                    args: {
                        name: "track"
                    }
                },
                {
                    name: "--release-status",
                    description: "Migrate to eas.json's releaseStatus property",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: ["upload:ios", "ui"],
            description: "Moved to eas submit in eas-cli",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--verbose",
                    description: "Migrate to eas submit --verbose",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--latest",
                    description: "Migrate to eas submit --latest",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--id",
                    description: "Migrate to eas submit --id <id>",
                    args: {
                        name: "id"
                    }
                },
                {
                    name: "--path",
                    description: "Migrate to eas submit --path <path>",
                    args: {
                        name: "path"
                    }
                },
                {
                    name: "--url",
                    description: "Migrate to eas submit --url <url>",
                    args: {
                        name: "url"
                    }
                },
                {
                    name: "--apple-id",
                    description: "Migrate to eas.json's appleId property",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--itc-team-id",
                    description: "Migrate to eas.json's appleTeamId property",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--app-name",
                    description: "Migrate to eas.json's appName property",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--company-name",
                    description: "Migrate to eas.json's companyName property",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--sku",
                    description: "Migrate to eas.json's sku property",
                    args: {
                        name: "sku"
                    }
                },
                {
                    name: "--language",
                    description: "Migrate to eas.json's language property",
                    args: {
                        name: "language"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: ["url", "u"],
            description: "Log a URL for opening the project in Expo Go",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--dev-client",
                    description: "Experimental: Starts the bundler for use with the expo-development-client",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--scheme",
                    description: "Custom URI protocol to use with a development build",
                    args: {
                        name: "scheme"
                    }
                },
                {
                    name: ["-a", "--android"],
                    description: "Opens your app in Expo Go on a connected Android device",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-i", "--ios"],
                    description: "Opens your app in Expo Go in a currently running iOS simulator on your computer",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-w", "--web"],
                    description: "Opens your app in a web browser",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: ["-m", "--host"],
                    description: 'Lan (default), tunnel, localhost. Type of host to use. "tunnel" allows you to view your link on other networks',
                    args: {
                        name: "mode"
                    }
                },
                {
                    name: "--tunnel",
                    description: "Same as --host tunnel",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--lan",
                    description: "Same as --host lan",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--localhost",
                    description: "Same as --host localhost",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--offline",
                    description: "Allows this command to run while offline",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "url:ipa",
            description: "Log the download URL for the standalone iOS binary",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--public-url",
                    description: "The URL of an externally hosted manifest (for self-hosted apps)",
                    args: {
                        name: "url"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "url:apk",
            description: "Log the download URL for the standalone Android binary",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--public-url",
                    description: "The URL of an externally hosted manifest (for self-hosted apps)",
                    args: {
                        name: "url"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "webhooks",
            description: "List all webhooks for a project",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "webhooks:add",
            description: "Add a webhook to a project",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--url",
                    description: "URL to request. (Required)",
                    args: {
                        name: "url"
                    }
                },
                {
                    name: "--event",
                    description: "Event type that triggers the webhook. [build] (Required)",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--secret",
                    description: "Secret used to create a hash signature of the request payload, provided in the 'Expo-Signature' header",
                    args: {
                        name: "secret"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "webhooks:remove",
            description: "Delete a webhook",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--id",
                    description: "ID of the webhook to remove",
                    args: {
                        name: "id"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        },
        {
            name: "webhooks:update",
            description: "Update an existing webhook",
            args: {
                name: "path"
            },
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Output usage information"
                },
                {
                    name: "--id",
                    description: "ID of the webhook to update",
                    args: {
                        name: "id"
                    }
                },
                {
                    name: "--url",
                    description: "URL the webhook will request",
                    args: {
                        name: "url"
                    }
                },
                {
                    name: "--event",
                    description: "Event type that triggers the webhook. [build]",
                    args: {
                        name: "boolean"
                    }
                },
                {
                    name: "--secret",
                    description: "Secret used to create a hash signature of the request payload, provided in the 'Expo-Signature' header",
                    args: {
                        name: "secret"
                    }
                },
                {
                    name: "--config",
                    description: "Deprecated: Use app.config.js to switch config files instead",
                    args: {
                        name: "file"
                    }
                }
            ]
        }
    ]
};
export default completionSpec;
