import type { CommandSpec, OptionSpec } from "../spec.types";
const commonOptions: OptionSpec[] = [
    {
        name: ["--config-path", "-c"],
        description: "Specify the path to the configuration file",
        args: {
            name: "path"
        }
    },
    {
        name: ["--sake-app-path", "-s"],
        description: "Specify the path for the SakeApp package",
        args: {
            name: "path"
        }
    }
];
const commonCommandSpecificOptions: OptionSpec[] = [
    {
        name: "--case-converting-strategy",
        description: "Specify the strategy for converting command names' case",
        args: {
            name: "strategy"
        }
    },
    {
        name: ["--sake-app-prebuilt-binary-path", "-b"],
        description: "Specify the path to the prebuilt SakeApp binary",
        args: {
            name: "path"
        }
    }
];
const completionSpec: CommandSpec = {
    name: "sake",
    description: "🍶 Swift-based utility for managing project commands, inspired by Make",
    subcommands: [
        {
            name: "init",
            description: "Initialize a new SakeApp project template for defining commands",
            options: [...commonOptions]
        },
        {
            name: "clean",
            description: "Remove all build artifacts generated by the SakeApp to ensure a clean state for future builds",
            options: [...commonOptions]
        },
        {
            name: "edit",
            description: "Open the SakeApp in Xcode (macOS only)",
            options: [...commonOptions]
        },
        {
            name: "list",
            description: "List all available commands defined in the SakeApp",
            options: [
                ...commonOptions,
                ...commonCommandSpecificOptions,
                {
                    name: ["--json", "-j"],
                    description: "Output the list of commands in JSON format"
                }
            ]
        },
        {
            name: "build",
            description: "Manually trigger a rebuild of the SakeApp",
            options: [
                ...commonOptions,
                {
                    name: "--show-bin-path",
                    description: "Print the path to the built SakeApp executable"
                }
            ]
        },
        {
            name: "run",
            description: "Run the specified command from the SakeApp",
            args: {
                name: "command",
                description: "The command to run"
            },
            options: [...commonOptions, ...commonCommandSpecificOptions]
        }
    ],
    options: [
        {
            name: ["--help", "-h"],
            description: "Show help information"
        },
        {
            name: "--version",
            description: "Show the version"
        }
    ]
};
export default completionSpec;
