import { filepaths } from "@fig/autocomplete-generators";
// Autogenerated by @fig/complete-commander
import type { CommandSpec } from "../../spec.types";
const completionSpec: CommandSpec = {
    name: "@withfig/autocomplete-tools",
    description: "Dev tools for fig's autocomplete",
    subcommands: [
        {
            name: "init",
            description: "Initialize fig custom spec boilerplate in current directory",
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Display help for command"
                }
            ]
        },
        {
            name: "create-spec",
            description: "Create spec with given name",
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Display help for command"
                }
            ],
            args: { name: "name" }
        },
        {
            name: "compile",
            description: "Compile specs in the current directory",
            options: [
                {
                    name: ["-w", "--watch"],
                    description: "Watch files and re-compile on change"
                },
                {
                    name: ["-h", "--help"],
                    description: "Display help for command"
                }
            ]
        },
        {
            name: "dev",
            description: "Watch for changes and compile specs",
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Display help for command"
                }
            ]
        },
        {
            name: "merge",
            description: "Deep merge new spec into old spec",
            options: [
                {
                    name: ["-n", "--new-file"],
                    description: "Create a new spec file instead of updating the old one",
                    args: { name: "path" }
                },
                {
                    name: ["-i", "--ignore-props"],
                    description: "The props that should always be overridden",
                    args: { name: "props" }
                },
                {
                    name: "--ignore-command-props",
                    description: "The command props that should always be overridden",
                    args: { name: "props" }
                },
                {
                    name: "--ignore-option-props",
                    description: "The option props that should always be overridden",
                    args: { name: "props" }
                },
                {
                    name: "--ignore-arg-props",
                    description: "The arg props that should always be overridden",
                    args: { name: "props" }
                },
                {
                    name: ["-p", "--preset"],
                    description: "Use a preset",
                    args: {
                        name: "name"
                    }
                },
                {
                    name: ["-h", "--help"],
                    description: "Display help for command"
                }
            ],
            args: [
                { name: "oldspec" },
                { name: "newspec" }
            ]
        },
        {
            name: "version",
            subcommands: [
                {
                    name: "add-diff",
                    description: "Generate version diff from new spec and add into old spec",
                    options: [
                        {
                            name: ["-n", "--new-path"],
                            description: "The root folder where the updated spec will be saved. Note: this must NOT include the folder spec name",
                            args: { name: "path" }
                        },
                        {
                            name: "--cwd",
                            description: "Resolve the spec name relative to this directory",
                            args: { name: "path" }
                        },
                        {
                            name: "--use-minor-base",
                            description: "Create a new version file per minor version"
                        },
                        {
                            name: ["-h", "--help"],
                            description: "Display help for command"
                        }
                    ],
                    args: [
                        { name: "specName" },
                        {
                            name: "newSpecFilePath"
                        },
                        { name: "diffVersion" }
                    ]
                },
                {
                    name: "init-spec",
                    description: "Generate versioned spec in folder specified by path",
                    options: [
                        {
                            name: "--cwd",
                            description: "Generate the spec relative to this directory",
                            args: { name: "path" }
                        },
                        {
                            name: ["-h", "--help"],
                            description: "Display help for command"
                        }
                    ],
                    args: { name: "name" }
                },
                {
                    name: "precompute-specs",
                    description: "[Unimplemented] Precompute versioned specs before publishing the specs repo (unimplemented)",
                    options: [
                        {
                            name: ["-h", "--help"],
                            description: "Display help for command"
                        }
                    ],
                    args: { name: "files" }
                },
                {
                    name: "help",
                    description: "Display help for command",
                    args: { name: "command" }
                }
            ],
            options: [
                {
                    name: ["-h", "--help"],
                    description: "Display help for command"
                }
            ]
        },
        {
            name: "help",
            description: "Display help for command",
            args: { name: "command" }
        }
    ],
    options: [
        { name: ["-V", "--version"], description: "Output the version number" },
        {
            name: ["-h", "--help"],
            description: "Display help for command"
        }
    ]
};
export default completionSpec;
