/**
 * Generates every action/config artifact from the TypeScript source of truth
 * (the action catalog + default-config-values.ts), so there is no second place
 * to maintain (steps 26 + K):
 *   - src-tauri/src/actions.generated.rs   (the Rust action list the CLI uses)
 *   - docs/actions.md                      (the human catalogue)
 *   - src-tauri/src/default_{windows,linux,macos}.config
 *
 * `--check` fails if any generated file on disk differs from a fresh render (CI,
 * via `pnpm lint`).
 *
 * `--site` also writes the website page into the sibling `meetcogno` repo.
 *
 * Run: `npx tsx scripts/generate-actions.ts [--check] [--site]`.
 */
import { globSync, readFileSync, writeFileSync } from "node:fs";
import {
  defaultSettings,
  featureKeybinds,
  platformSettingOverrides,
} from "../src/core/infrastructure/config/models/default-config-values";
import { coreActionCatalog } from "../src/core/workbench/actions/catalog";

const REPO_ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const GENERATED_RS = `${REPO_ROOT}/src-tauri/src/actions.generated.rs`;
const DOCS_MD = `${REPO_ROOT}/docs/actions.md`;
const SITE_MD = `${REPO_ROOT}/../meetcogno/src/content/docs/config/actions.md`;
const OS_CONFIGS = ["windows", "linux", "macos"] as const;
type Os = (typeof OS_CONFIGS)[number];
const configPath = (os: Os) => `${REPO_ROOT}/src-tauri/src/default_${os}.config`;

type ActionRow = { readonly name: string; readonly description: string };

/** Feature action names and titles, read textually so no Angular is loaded. */
function featureActions(): ActionRow[] {
  const rows: ActionRow[] = [];
  // Feature definitions live under features/, plus a few workbench-owned ones in
  // core/ (e.g. workspace -> open_workspace).
  const files = [
    ...globSync(`${REPO_ROOT}/src/features/**/*.feature-definition.ts`),
    ...globSync(`${REPO_ROOT}/src/core/**/*.feature-definition.ts`),
  ];
  for (const file of files.sort()) {
    const text = readFileSync(file, "utf8");
    const name = text.match(/actionName:\s*"([a-z0-9_]+)"/)?.[1];
    const title = text.match(/title:\s*"([^"]+)"/)?.[1];
    if (name) {
      rows.push({ name, description: title ? `Open the ${title} panel` : name });
    }
  }
  return rows;
}

function allActions(): ActionRow[] {
  const core = coreActionCatalog.map((entry) => ({
    name: entry.name,
    description: entry.description,
  }));
  return [...core, ...featureActions()];
}

function rustString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function renderRust(): string {
  const rows = allActions()
    .map((row) => `    ("${rustString(row.name)}", "${rustString(row.description)}"),`)
    .join("\n");
  return (
    `// @generated by scripts/generate-actions.ts - do not edit.
// Run ` +
    "`npx tsx scripts/generate-actions.ts`" +
    ` after changing the action catalog.

/// Every action name the CLI knows, paired with its description.
pub const COGNO_ACTIONS: &[(&str, &str)] = &[
${rows}
];
`
  );
}

function comboFor(action: (typeof coreActionCatalog)[number], os: Os): string {
  const keys = action.defaultKeys;
  if (!keys) {
    return "";
  }
  const perOs = os === "macos" && keys.macos ? keys.macos : keys.default;
  return perOs.map((key) => key.combo).join(", ") || "";
}

function featureComboFor(actionName: string, os: Os): string {
  return featureKeybinds
    .filter((entry) => entry.action === actionName)
    .map((entry) => (os === "macos" && entry.macos ? entry.macos : entry.combo))
    .join(", ");
}

/**
 * Headings of the action reference. An action belongs to the first group whose
 * pattern matches its name; the last group takes whatever is left.
 */
const ACTION_GROUPS: ReadonlyArray<{ title: string; match: RegExp }> = [
  { title: "Clipboard", match: /^(copy|cut|paste)$/ },
  { title: "Text selection", match: /^select_(all|text_|word_)/ },
  { title: "Cursor movement", match: /^go_to_/ },
  { title: "Input line and buffer", match: /^(clear_|delete_)/ },
  { title: "Autocomplete and history", match: /^(trigger_|cycle_tab$)/ },
  { title: "Tabs", match: /^(new_tab|close_tab|close_other_tabs|close_all_tabs|select_.*tab)/ },
  { title: "Panes", match: /^(split_|maximize_pane|minimize_pane|select_.*pane|close_terminal)/ },
  { title: "Shell profiles", match: /^open_shell_/ },
  { title: "Workspaces", match: /^select_workspace_/ },
  { title: "Feature panels", match: /^open_(?!config$|documentation$|about$)/ },
  { title: "Window", match: /^(new_window|close_window|minimize_window|quit)$/ },
  { title: "App", match: /./ },
];

type DocRow = { name: string; description: string; win: string; mac: string };

function docRows(): DocRow[] {
  const core = coreActionCatalog.map((action) => ({
    name: action.name,
    description: action.description,
    win: comboFor(action, "windows") || "-",
    mac: comboFor(action, "macos") || "-",
  }));
  const features = featureActions().map((row) => ({
    name: row.name,
    description: row.description,
    win: featureComboFor(row.name, "windows") || "-",
    mac: featureComboFor(row.name, "macos") || "-",
  }));
  return [...core, ...features];
}

/** The grouped reference tables, shared by `docs/actions.md` and the website page. */
function renderDocsBody(): string {
  const rows = docRows();
  const lines: string[] = [];
  for (const [index, group] of ACTION_GROUPS.entries()) {
    const earlier = ACTION_GROUPS.slice(0, index);
    const members = rows.filter(
      (row) => group.match.test(row.name) && !earlier.some((g) => g.match.test(row.name)),
    );
    if (members.length === 0) continue;
    lines.push(`## ${group.title}`, "");
    lines.push("| Action | Description | Windows/Linux | macOS |", "| --- | --- | --- | --- |");
    for (const row of members) {
      lines.push(`| \`${row.name}\` | ${row.description} | ${row.win} | ${row.mac} |`);
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function renderDocs(): string {
  return [
    "<!-- @generated by scripts/generate-actions.ts - do not edit. -->",
    "# Actions",
    "",
    "Every action, its description and default keybinding. `-` means no default keybinding.",
    "",
    renderDocsBody(),
  ].join("\n");
}

/** The same reference as a Starlight page of the website (sibling `meetcogno` repo). */
function renderSitePage(): string {
  return [
    "---",
    "title: All actions",
    "description: Reference of every Cogno action with its default keybinding.",
    "slug: docs/config/actions",
    "---",
    "",
    "<!-- Generated by Cogno/scripts/generate-actions.ts. Do not edit. -->",
    "",
    "Every action can be bound to a key, run from the command palette, or triggered from the",
    "CLI. The tables show the default keybinding per platform; `-` means the action has none.",
    "",
    "- Bind a key: `keybind = Ctrl+M=minimize_window`, see [Keybindings](/docs/config/keybindings)",
    "- Run from a script: `cogno action run <name>`, see [CLI](/docs/cli#cogno-action)",
    "",
    "A feature's `open_…` action disappears when the feature is",
    "[switched off](/docs/config/settings#features).",
    "",
    renderDocsBody(),
  ].join("\n");
}

type Nested = { [key: string]: string | Nested };

function deepMerge(base: Nested, override: Nested): Nested {
  const out: Nested = { ...base };
  for (const [key, value] of Object.entries(override)) {
    const current = out[key];
    out[key] =
      typeof value === "object" && typeof current === "object" ? deepMerge(current, value) : value;
  }
  return out;
}

function flatten(node: Nested, prefix = ""): Array<[string, string]> {
  const rows: Array<[string, string]> = [];
  for (const [key, value] of Object.entries(node)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof value === "string") {
      rows.push([path, value]);
    } else {
      rows.push(...flatten(value, path));
    }
  }
  return rows;
}

function keyFlags(entry: { always?: boolean; performable?: boolean }): string {
  return `${entry.always ? "always:" : ""}${entry.performable ? "performable:" : ""}`;
}

/** Render a full default_<os>.config from the TS source of truth (step K). */
function renderConfig(os: Os): string {
  const merged = deepMerge(
    defaultSettings as unknown as Nested,
    (platformSettingOverrides as Record<string, Nested>)[os] ?? {},
  );
  const lines: string[] = ["# @generated by scripts/generate-actions.ts - do not edit.", ""];
  for (const [key, value] of flatten(merged)) {
    lines.push(value === "" ? `${key} =` : `${key} = ${value}`);
  }
  lines.push("", "# Keybindings");
  for (const action of coreActionCatalog) {
    if (!action.defaultKeys) continue;
    const keys =
      os === "macos" && action.defaultKeys.macos
        ? action.defaultKeys.macos
        : action.defaultKeys.default;
    for (const key of keys) {
      lines.push(`keybind = ${keyFlags(key)}${key.combo}=${action.name}`);
    }
  }
  for (const entry of featureKeybinds) {
    const combo = os === "macos" && entry.macos ? entry.macos : entry.combo;
    lines.push(`keybind = ${keyFlags(entry)}${combo}=${entry.action}`);
  }
  return `${lines.join("\n")}\n`;
}

function main(): void {
  const outputs: Array<[string, string]> = [
    [GENERATED_RS, renderRust()],
    [DOCS_MD, renderDocs()],
    ...OS_CONFIGS.map((os): [string, string] => [configPath(os), renderConfig(os)]),
  ];

  if (process.argv.includes("--check")) {
    const stale = outputs
      .filter(([path, content]) => readFileSync(path, "utf8") !== content)
      .map(([path]) => path.replace(`${REPO_ROOT}/`, ""));
    if (stale.length > 0) {
      console.error(`Stale generated files - run \`pnpm generate:actions\`:\n${stale.join("\n")}`);
      process.exit(1);
    }
    console.log("actions: all generated files current (Rust list, docs, configs).");
    return;
  }

  for (const [path, content] of outputs) {
    writeFileSync(path, content);
  }
  console.log("Wrote actions.generated.rs, docs/actions.md and the three default_*.config files.");
  if (process.argv.includes("--site")) {
    writeFileSync(SITE_MD, renderSitePage());
    console.log(`Wrote ${SITE_MD}`);
  }
}

main();
