/**
 * Generates every action/config artifact from the TypeScript source of truth
 * (the action catalog + default-config-values.ts), so there is no second place
 * to maintain (steps 26 + K):
 *   - src-tauri/src/actions.generated.rs   (the Rust action list the CLI uses)
 *   - docs/actions.md                      (the human catalogue)
 *   - src-tauri/src/default_{windows,linux,macos}.config
 *
 * `--check` fails if any generated file on disk differs from a fresh render (CI,
 * via `pnpm lint`). `--parity` is the one-time migration aid: it compares a fresh
 * render against the current config files semantically (settings + keybinds).
 *
 * Run: `npx tsx scripts/generate-actions.ts [--check|--parity]`.
 */
import { globSync, readFileSync, writeFileSync } from "node:fs";
import { coreActionCatalog } from "../src/core/workbench/actions/catalog";
import {
  defaultSettings,
  featureKeybinds,
  platformSettingOverrides,
} from "../src/core/infrastructure/config/models/default-config-values";

const REPO_ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const GENERATED_RS = `${REPO_ROOT}/src-tauri/src/actions.generated.rs`;
const DOCS_MD = `${REPO_ROOT}/docs/actions.md`;
const OS_CONFIGS = ["windows", "linux", "macos"] as const;
type Os = (typeof OS_CONFIGS)[number];
const configPath = (os: Os) => `${REPO_ROOT}/src-tauri/src/default_${os}.config`;

type ActionRow = { readonly name: string; readonly description: string };

/** Feature action names and titles, read textually so no Angular is loaded. */
function featureActions(): ActionRow[] {
  const rows: ActionRow[] = [];
  // Feature definitions live under features/, plus a few workbench-owned ones in
  // core/ (e.g. workspace -> open_workspace).
  const files = [
    ...globSync(`${REPO_ROOT}/src/features/**/*.feature-definition.ts`),
    ...globSync(`${REPO_ROOT}/src/core/**/*.feature-definition.ts`),
  ];
  for (const file of files.sort()) {
    const text = readFileSync(file, "utf8");
    const name = text.match(/actionName:\s*"([a-z0-9_]+)"/)?.[1];
    const title = text.match(/title:\s*"([^"]+)"/)?.[1];
    if (name) {
      rows.push({ name, description: title ? `Open the ${title} panel` : name });
    }
  }
  return rows;
}

function allActions(): ActionRow[] {
  const core = coreActionCatalog.map((entry) => ({ name: entry.name, description: entry.description }));
  return [...core, ...featureActions()];
}

function rustString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function renderRust(): string {
  const rows = allActions()
    .map((row) => `    ("${rustString(row.name)}", "${rustString(row.description)}"),`)
    .join("\n");
  return `// @generated by scripts/generate-actions.ts - do not edit.
// Run `+"`npx tsx scripts/generate-actions.ts`"+` after changing the action catalog.

/// Every action name the CLI knows, paired with its description.
pub const COGNO_ACTIONS: &[(&str, &str)] = &[
${rows}
];
`;
}

function comboFor(action: (typeof coreActionCatalog)[number], os: Os): string {
  const keys = action.defaultKeys;
  if (!keys) {
    return "";
  }
  const perOs = os === "macos" && keys.macos ? keys.macos : keys.default;
  return perOs.map((key) => key.combo).join(", ") || "";
}

function renderDocs(): string {
  const lines = [
    "<!-- @generated by scripts/generate-actions.ts - do not edit. -->",
    "# Actions",
    "",
    "Every action, its description and default keybinding.",
    "",
    "| Action | Description | Windows/Linux | macOS |",
    "| --- | --- | --- | --- |",
  ];
  for (const action of coreActionCatalog) {
    const win = comboFor(action, "windows") || "-";
    const mac = comboFor(action, "macos") || "-";
    lines.push(`| \`${action.name}\` | ${action.description} | ${win} | ${mac} |`);
  }
  for (const row of featureActions()) {
    lines.push(`| \`${row.name}\` | ${row.description} | - | - |`);
  }
  return `${lines.join("\n")}\n`;
}



type Nested = { [key: string]: string | Nested };

function deepMerge(base: Nested, override: Nested): Nested {
  const out: Nested = { ...base };
  for (const [key, value] of Object.entries(override)) {
    const current = out[key];
    out[key] =
      typeof value === "object" && typeof current === "object"
        ? deepMerge(current, value)
        : value;
  }
  return out;
}

function flatten(node: Nested, prefix = ""): Array<[string, string]> {
  const rows: Array<[string, string]> = [];
  for (const [key, value] of Object.entries(node)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof value === "string") {
      rows.push([path, value]);
    } else {
      rows.push(...flatten(value, path));
    }
  }
  return rows;
}

function keyFlags(entry: { always?: boolean; performable?: boolean }): string {
  return `${entry.always ? "always:" : ""}${entry.performable ? "performable:" : ""}`;
}

/** Render a full default_<os>.config from the TS source of truth (step K). */
function renderConfig(os: Os): string {
  const merged = deepMerge(
    defaultSettings as unknown as Nested,
    (platformSettingOverrides as Record<string, Nested>)[os] ?? {},
  );
  const lines: string[] = ["# @generated by scripts/generate-actions.ts - do not edit.", ""];
  for (const [key, value] of flatten(merged)) {
    lines.push(value === "" ? `${key} =` : `${key} = ${value}`);
  }
  lines.push("", "# Keybindings");
  for (const action of coreActionCatalog) {
    if (!action.defaultKeys) continue;
    const keys = os === "macos" && action.defaultKeys.macos ? action.defaultKeys.macos : action.defaultKeys.default;
    for (const key of keys) {
      lines.push(`keybind = ${keyFlags(key)}${key.combo}=${action.name}`);
    }
  }
  for (const entry of featureKeybinds) {
    const combo = os === "macos" && entry.macos ? entry.macos : entry.combo;
    lines.push(`keybind = ${keyFlags(entry)}${combo}=${entry.action}`);
  }
  return `${lines.join("\n")}\n`;
}

/** Parse a config into a comparable shape: settings key/value map + keybind set. */
function parseConfigSemantic(text: string): { settings: Map<string, string>; keybinds: Set<string> } {
  const settings = new Map<string, string>();
  const keybinds = new Set<string>();
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#") || trimmed.startsWith(";")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    if (key === "keybind") {
      const [lhs, action] = value.split("=");
      if (!action) continue;
      const tokens = lhs.split(":").map((token) => token.trim()).filter(Boolean);
      const combo = tokens.pop();
      const flags = [...tokens].sort().join(":");
      keybinds.add(`${flags}|${combo}|${action.trim()}`);
    } else {
      settings.set(key, value);
    }
  }
  return { settings, keybinds };
}

/** One-time (--parity): generated configs vs the current files, semantically. */
function configParity(): string[] {
  const problems: string[] = [];
  for (const os of OS_CONFIGS) {
    const current = parseConfigSemantic(readFileSync(configPath(os), "utf8"));
    const generated = parseConfigSemantic(renderConfig(os));
    for (const [key, value] of current.settings) {
      if (generated.settings.get(key) !== value) {
        problems.push(`${os} setting ${key}: current="${value}" generated="${generated.settings.get(key)}"`);
      }
    }
    for (const key of generated.settings.keys()) {
      if (!current.settings.has(key)) problems.push(`${os} setting ${key}: only in generated`);
    }
    for (const keybind of current.keybinds) {
      if (!generated.keybinds.has(keybind)) problems.push(`${os} keybind only in current: ${keybind}`);
    }
    for (const keybind of generated.keybinds) {
      if (!current.keybinds.has(keybind)) problems.push(`${os} keybind only in generated: ${keybind}`);
    }
  }
  return problems;
}

function main(): void {
  if (process.argv.includes("--parity")) {
    const problems = configParity();
    if (problems.length > 0) {
      console.error(`Config parity problems (${problems.length}):\n${problems.join("\n")}`);
      process.exit(1);
    }
    console.log("Config parity: generated configs match the current files (settings + keybinds).");
    return;
  }
  const outputs: Array<[string, string]> = [
    [GENERATED_RS, renderRust()],
    [DOCS_MD, renderDocs()],
    ...OS_CONFIGS.map((os): [string, string] => [configPath(os), renderConfig(os)]),
  ];

  if (process.argv.includes("--check")) {
    const stale = outputs
      .filter(([path, content]) => readFileSync(path, "utf8") !== content)
      .map(([path]) => path.replace(`${REPO_ROOT}/`, ""));
    if (stale.length > 0) {
      console.error(
        `Stale generated files - run \`pnpm generate:actions\`:\n${stale.join("\n")}`,
      );
      process.exit(1);
    }
    console.log("actions: all generated files current (Rust list, docs, configs).");
    return;
  }

  for (const [path, content] of outputs) {
    writeFileSync(path, content);
  }
  console.log("Wrote actions.generated.rs, docs/actions.md and the three default_*.config files.");
}

main();
